server:  
  port: ${PORT:2222}

# Spring properties
spring:  
  application:
    name: contacts-client

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
microservicio:
  contact:
    name: edge-server
    findAllUrl: http://${microservicio.contact.name}/contacts/findall/
    saveUrl: http://${microservicio.contact.name}/contacts/save/
    deleteUrl: http://${microservicio.contact.name}/contacts/delete/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest  
